name:                GLaDOS
version:             0.1.0.0
github:              "hinivir/GLaDOS"
license:             BSD3
author:              "Pierre-Louis Leroy, Cyprien Nguyen-Van-Vien, Virgile Berrier, Damien Benais-Captal, Viktor Bruggeman"
maintainer:          "pierre-louis.leroy@epitech.eu, cyprien.nguyen-van-vien@epitech.eu, virgile.berrier@epitech.eu, damien.benais-captal@epitech.eu, viktor.bruggeman@epitech.eu"
copyright:           "2023"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/hinivir/GLaDOS#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  glados:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GLaDOS

tests:
  glados-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GLaDOS
    - HUnit
